name: Github_registry

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Build_Push_Docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and push the image
      run:  |
        docker login --username jaivignesh-vunet --password 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 ghcr.io
        docker build . -t ghcr.io/jaivignesh-vunet/testimage:latest
        docker push ghcr.io/jaivignesh-vunet/testimage:latest
      
