name: Send Email
on:
  push:
    branches:
      - master

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send email
        run: |
          echo "To: jaivignesh@vunetsystems.com" >> email.txt
          echo "Subject: Repository Details" >> email.txt
          echo "Organization: $ORG_NAME" >> email.txt
          echo "Repository: $REPO_NAME" >> email.txt
          cat email.txt | sendmail -f jaivignesh@vunetsystems.com
