name: Send Email
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install actions/email
        run: |
          sudo apt-get update
          sudo apt-get install actions/email

      - name: Send mail
        uses: actions/email@v1
        with:
          from: "jaivignesh@vunetsystems.com"
          to: "jaivignesh@vunetsystems.com"
          subject: "Test email"
          body: "This is a test email."
