name: Print Organization and Repository Details
on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  print_details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mailjet_rest
      
      - name: Set environment variables
        run: |
          echo "ORG_NAME=<organization>" >> $GITHUB_ENV
          echo "REPO_NAME=$GITHUB_REPOSITORY" >> $GITHUB_ENV
      
      - name: Print details
        run: python pytest.py
